language: ruby
rvm:
- 2.5
- 2.6
install:
- bundle install --without development
env:
  global:
    secure: YFsii8BNgSr/iuFiM+o9840H6lnsXMX9Mbz8gpVranJtCmygKWuHL5zJ1q9hy6vBCmOui8pp2gpiJK8fxz+94qDIrf/5DnXdkqFfjgF5OPMv4quan6zSIlxDlPTZu9CjTzuxoO2hxLS8RpclBveKdzlEPcY+kWg3aAiVsadlXD4X92BKQqd1NqRlAigfQcdWHR0/8CjpWHG15N+ZkG8UFpli3n5hP/FhbcfVdtUeXPDowPzz/dEe3SoJLIOKuc8i7QL/BeDH0XlikaNnazCnJ0ejgzkzyN/bWElTgbLYTTN4ofXZQLLxvfuhFUm+9HBp8NaWDfVue3ZMWHcY2zBWVIxTGdisEwrSzDTwcnOo31oBvystK2kuxdGWiXzZCkiJLILy6djXoHZySF7g+FnTdhCplC+HMZqGxN1NAorjrsA4SuIiIySwVuFxU2F/RJikcjFNT5rr+mgYGOWNnGouwuEFBblNNwFcIwHP8C/evR0VnES9kAHl+/B9OiO/nMi4kcOfsGtbVa9IoAgVZS2Guilnh2GZRpR7k9KJkBRqSu0sLxpABVYFOJwuvbFhF3tM6GV0yzalbB/TbOKj424dg1i8zzmoc86EtfA3FBdGSg61Zr53GMvK6WDudMr2lOUrmf6zOdBcMkSMeAxHTJdcPZo9CCvhqUbyjLlbynQKGsw=
